subsystem=APS
component=PEAS.ProcedureSetupService
publish {
	description = """
Setup Service published events - apsNotificationEvent
"""

	events=[
        {
			name=apsCommandFailureEvent
			archive=true
			description="""Event used to communicate a command failure to the user interface and/or Alignment Procedure Sequencer."""
			maxRate = 1
            category=EVENT
			archive=true
			attributes=[
				{
					name=sourceAssembly
					description="""The user readable name of the source assembly or service that published the event"""
					type=string
                }
				{
					name=message
					description="""Failure message supplied by the event source."""
					type=string
                }				
                {
					name=recoveryState
					description="""For failures and errors that have recovery modes (e.g. motion assemblies and detector assemblies) a state for the progress of the recovery is given: started, completed, aborted.  For failures that do not support auto recovery, the state is NOT USED."""
					enum=["STARTED", "COMPLETED", "ABORTED", "NOT_USED"]
                }
				{
					name=recoveryRetryIndex
					description="""The current auto-recovery retry number."""
					type=integer
                    units=NoUnits
                }
				{
					name=recoveryRetryCount
					description="""The total number of auto-recovery retries before recovery is abandoned."""
					type=integer
                    units=NoUnits
                }
                {
					name=recoveryRetryState
					description="""Indicates if the current retry succeeded or failed."""
					enum=["FAILURE", "SUCCESS"]
                }
			]
		}
	]
}
