subsystem=APS
component=ICS.Computation
publish {
events=[
		{
			name=status
			description="""Computation status event"""
			maxRate = 1
			archive=true
            category=STATUS
			attributes=[
				{
					name=assemblyState
					description="""Current Assembly State"""
					enum = ["READY", "DEGRADED", "FAULTED"]
				}
				{
					name=commandState
					description="""Status of last command"""
					enum = ["IDLE", "PROCESSING", "ERROR_RECOVERY", "FAILED"]
				}
			]
		}
        {
			name=apsCommandFailureEvent
			archive=true
			description="""Event used to communicate a command failure to the user interface and/or Alignment Procedure Sequencer."""
			maxRate = 1
            category=EVENT
			archive=true
			attributes=[
				{
					name=sourceAssembly
					description="""The user readable name of the source assembly or service that published the event"""
					type=string
                }
				{
					name=message
					description="""Failure message supplied by the event source."""
					type=string
                }				
                {
					name=recoveryState
					description="""For failures and errors that have recovery modes (e.g. motion assemblies and detector assemblies) a state for the progress of the recovery is given: started, completed, aborted.  For failures that do not support auto recovery, the state is NOT USED."""
					enum=["STARTED", "COMPLETED", "ABORTED", "NOT_USED"]
                }
				{
					name=recoveryRetryIndex
					description="""The current auto-recovery retry number."""
					type=integer
                    units=NoUnits
                }
				{
					name=recoveryRetryCount
					description="""The total number of auto-recovery retries before recovery is abandoned."""
					type=integer
                    units=NoUnits
                }
                {
					name=recoveryRetryState
					description="""Indicates if the current retry succeeded or failed."""
					enum=["FAILURE", "SUCCESS"]
                }
			]
		}

        {
			name=startupMetrics
			description="""Assembly startup metrics"""
			maxRate = 1
            category=ARCHIVE
			archive=true
			attributes=[
				{
					name=initStartTime
					description="""Assembly initialization start time"""
					type=taiDate
				}
				{
					name=initCompletedTime
					description="""Assembly initialization completed time"""
					type=taiDate
				}

			]
		}

      
    ]
    
    alarms = [
        {
            name = assemblyFaulted
            description = """Assembly is in the faulted state."""
            // TODO FIXME: The fields below were automatically added and should be updated manually
            severityLevels = [Major]
            location = "Software"
            alarmType = Calculated
            probableCause = "TBD..."
            operatorResponse = "TBD..."
            autoAck = false
            latched = false
        }
        {
            name = imageDataAccessTimeSlow
            description = """The time to access image data exceeds warning threshold."""
            // TODO FIXME: The fields below were automatically added and should be updated manually
            severityLevels = [Warning]
            location = "Software"
            alarmType = Calculated
            probableCause = "TBD..."
            operatorResponse = "TBD..."
            autoAck = false
            latched = false
        }
    ]
}

