subsystem=APS
component=PEAS.ExposureService

alarms = [

  {
    name            = "DiskLow"
    description     = "Remaining disk space below threshold."
    severityLevels  = [Warning]
    location        = "APS Shared Disk"
    alarmType       = Instrument
    probableCause   = "Disk space running low."
    operatorResponse= "Use APS Engineering User Interface to purge disk."
    autoAck         = false
    latched         = true
  },
  
  
]